services:
  mysql-db:
    image: library/mysql:8.0.4
    container_name: order_book
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order_password
      MYSQL_DATABASE: orders_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
