spring:
  application:
    name: order-book
  profiles:
    active: dev

  # MySQL configuration
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db
    username: order_user
    password: order_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA and hibernate configuration
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: orders_db

# Logging configuration
logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: INFO
    com.zaxxer.hikari: INFO
    org.springframework.boot: INFO
    com.example.orderbook: ERROR

# Swagger UI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true

server:
  port : 8080